# Generated by Django 4.0.4 on 2023-05-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(default='basic event description', max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(default='Fort Wayne, IN', max_length=50)),
            ],
        ),
    ]
